// <auto-generated />
using System;
using DernekYonetim.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DernekYonetim.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260514120000_BelgeDosyaIcerigi")]
    partial class BelgeDosyaIcerigi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // BuildTargetModel is used only by dotnet-ef tooling, not at runtime.
        }
    }
}
