// <auto-generated />
using System;
using DernekYonetim.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DernekYonetim.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260513084752_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DernekYonetim.Models.Aidat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<bool>("DekontOnaylandi")
                        .HasColumnType("boolean");

                    b.Property<string>("DekontUrl")
                        .HasColumnType("text");

                    b.Property<string>("Donem")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("OdemeDurumu")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("OdemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("OdemeYontemi")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OnaylayanId")
                        .HasColumnType("text");

                    b.Property<DateTime>("SonOdemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Tutar")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("UyeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UyeId", "Donem")
                        .IsUnique();

                    b.ToTable("Aidatlar");
                });

            modelBuilder.Entity("DernekYonetim.Models.Basvuru", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Adres")
                        .HasColumnType("text");

                    b.Property<string>("BasvuruNotu")
                        .HasColumnType("text");

                    b.Property<DateTime>("BasvuruTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BelgeUrl")
                        .HasColumnType("text");

                    b.Property<int>("Durum")
                        .HasColumnType("integer");

                    b.Property<string>("EkBilgiMesaji")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("IslemTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IslemYapanId")
                        .HasColumnType("text");

                    b.Property<string>("Meslek")
                        .HasColumnType("text");

                    b.Property<string>("RedNedeni")
                        .HasColumnType("text");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TcKimlik")
                        .HasColumnType("text");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Basvurular");
                });

            modelBuilder.Entity("DernekYonetim.Models.Belge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DosyaAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("DosyaBoyutu")
                        .HasColumnType("bigint");

                    b.Property<string>("DosyaTipi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DosyaYolu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ErisimSeviyesi")
                        .HasColumnType("integer");

                    b.Property<string>("Kategori")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("OncekiVersiyonId")
                        .HasColumnType("integer");

                    b.Property<int>("Versiyon")
                        .HasColumnType("integer");

                    b.Property<DateTime>("YuklemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("YukleyenId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("YukleyenId");

                    b.ToTable("Belgeler");
                });

            modelBuilder.Entity("DernekYonetim.Models.Bildirim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Mesaj")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("OkunduMu")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Tur")
                        .HasColumnType("integer");

                    b.Property<string>("UyeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("YonlendirmeUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UyeId");

                    b.ToTable("Bildirimler");
                });

            modelBuilder.Entity("DernekYonetim.Models.Duyuru", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("boolean");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("BitisTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GorselUrl")
                        .HasColumnType("text");

                    b.Property<int>("Hedef")
                        .HasColumnType("integer");

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("KamuoyunaAcik")
                        .HasColumnType("boolean");

                    b.Property<string>("OlusturanId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Ozet")
                        .HasColumnType("text");

                    b.Property<DateTime?>("YayinTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OlusturanId");

                    b.ToTable("Duyurular");
                });

            modelBuilder.Entity("DernekYonetim.Models.Etkinlik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Durum")
                        .HasColumnType("integer");

                    b.Property<string>("GorselUrl")
                        .HasColumnType("text");

                    b.Property<int>("Kategori")
                        .HasColumnType("integer");

                    b.Property<int?>("Kontenjan")
                        .HasColumnType("integer");

                    b.Property<string>("OlusturanId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Ucret")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<bool>("UcretsizMi")
                        .HasColumnType("boolean");

                    b.Property<string>("Yer")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OlusturanId");

                    b.ToTable("Etkinlikler");
                });

            modelBuilder.Entity("DernekYonetim.Models.EtkinlikKayit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Durum")
                        .HasColumnType("integer");

                    b.Property<int>("EtkinlikId")
                        .HasColumnType("integer");

                    b.Property<bool>("KatildiMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UyeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EtkinlikId");

                    b.HasIndex("UyeId", "EtkinlikId")
                        .IsUnique();

                    b.ToTable("EtkinlikKayitlari");
                });

            modelBuilder.Entity("DernekYonetim.Models.LogKaydi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Detay")
                        .HasColumnType("text");

                    b.Property<string>("IpAdresi")
                        .HasColumnType("text");

                    b.Property<string>("Olay")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UyeId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UyeId");

                    b.ToTable("LogKayitlari");
                });

            modelBuilder.Entity("DernekYonetim.Models.MaliHareket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BelgeUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("IslemTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kategori")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KaydEdenId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Tur")
                        .HasColumnType("integer");

                    b.Property<decimal>("Tutar")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("KaydEdenId");

                    b.ToTable("MaliHareketler");
                });

            modelBuilder.Entity("DernekYonetim.Models.Proje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("BitisTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DigerKategori")
                        .HasColumnType("text");

                    b.Property<int>("Durum")
                        .HasColumnType("integer");

                    b.Property<decimal?>("HedefBütce")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("KapakFotoUrl")
                        .HasColumnType("text");

                    b.Property<int>("Kategori")
                        .HasColumnType("integer");

                    b.Property<string>("OlusturanId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Sehir")
                        .HasColumnType("text");

                    b.Property<decimal?>("ToplamBagis")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("Ulke")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OlusturanId");

                    b.ToTable("Projeler");
                });

            modelBuilder.Entity("DernekYonetim.Models.ProjeBelge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("DosyaBoyutu")
                        .HasColumnType("bigint");

                    b.Property<string>("DosyaYoluVeyaLink")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KucukResimUrl")
                        .HasColumnType("text");

                    b.Property<int>("ProjeId")
                        .HasColumnType("integer");

                    b.Property<int>("Tur")
                        .HasColumnType("integer");

                    b.Property<DateTime>("YuklemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("YukleyenId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjeId");

                    b.HasIndex("YukleyenId");

                    b.ToTable("ProjeBelgeleri");
                });

            modelBuilder.Entity("DernekYonetim.Models.ProjeGuncelleme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IlerlemeYuzdesi")
                        .HasColumnType("integer");

                    b.Property<int>("ProjeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("YazanId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjeId");

                    b.HasIndex("YazanId");

                    b.ToTable("ProjeGuncellemeleri");
                });

            modelBuilder.Entity("DernekYonetim.Models.Uye", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Adres")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Meslek")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("ProfilFotoUrl")
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SonGiris")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TcKimlik")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("UyeNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("UyelikDurumu")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UyelikTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("UyeNo")
                        .IsUnique();

                    b.ToTable("Uyeler", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DernekYonetim.Models.Aidat", b =>
                {
                    b.HasOne("DernekYonetim.Models.Uye", "Uye")
                        .WithMany("Aidatlar")
                        .HasForeignKey("UyeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Uye");
                });

            modelBuilder.Entity("DernekYonetim.Models.Belge", b =>
                {
                    b.HasOne("DernekYonetim.Models.Uye", "Yukleyen")
                        .WithMany("Belgeler")
                        .HasForeignKey("YukleyenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Yukleyen");
                });

            modelBuilder.Entity("DernekYonetim.Models.Bildirim", b =>
                {
                    b.HasOne("DernekYonetim.Models.Uye", "Uye")
                        .WithMany("Bildirimler")
                        .HasForeignKey("UyeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Uye");
                });

            modelBuilder.Entity("DernekYonetim.Models.Duyuru", b =>
                {
                    b.HasOne("DernekYonetim.Models.Uye", "Olusturan")
                        .WithMany()
                        .HasForeignKey("OlusturanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Olusturan");
                });

            modelBuilder.Entity("DernekYonetim.Models.Etkinlik", b =>
                {
                    b.HasOne("DernekYonetim.Models.Uye", "Olusturan")
                        .WithMany()
                        .HasForeignKey("OlusturanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Olusturan");
                });

            modelBuilder.Entity("DernekYonetim.Models.EtkinlikKayit", b =>
                {
                    b.HasOne("DernekYonetim.Models.Etkinlik", "Etkinlik")
                        .WithMany("Kayitlar")
                        .HasForeignKey("EtkinlikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DernekYonetim.Models.Uye", "Uye")
                        .WithMany("EtkinlikKayitlari")
                        .HasForeignKey("UyeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Etkinlik");

                    b.Navigation("Uye");
                });

            modelBuilder.Entity("DernekYonetim.Models.LogKaydi", b =>
                {
                    b.HasOne("DernekYonetim.Models.Uye", "Uye")
                        .WithMany()
                        .HasForeignKey("UyeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Uye");
                });

            modelBuilder.Entity("DernekYonetim.Models.MaliHareket", b =>
                {
                    b.HasOne("DernekYonetim.Models.Uye", "KaydEden")
                        .WithMany()
                        .HasForeignKey("KaydEdenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KaydEden");
                });

            modelBuilder.Entity("DernekYonetim.Models.Proje", b =>
                {
                    b.HasOne("DernekYonetim.Models.Uye", "Olusturan")
                        .WithMany()
                        .HasForeignKey("OlusturanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Olusturan");
                });

            modelBuilder.Entity("DernekYonetim.Models.ProjeBelge", b =>
                {
                    b.HasOne("DernekYonetim.Models.Proje", "Proje")
                        .WithMany("Belgeler")
                        .HasForeignKey("ProjeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DernekYonetim.Models.Uye", "Yukleyen")
                        .WithMany()
                        .HasForeignKey("YukleyenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proje");

                    b.Navigation("Yukleyen");
                });

            modelBuilder.Entity("DernekYonetim.Models.ProjeGuncelleme", b =>
                {
                    b.HasOne("DernekYonetim.Models.Proje", "Proje")
                        .WithMany("Guncellemeler")
                        .HasForeignKey("ProjeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DernekYonetim.Models.Uye", "Yazan")
                        .WithMany()
                        .HasForeignKey("YazanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proje");

                    b.Navigation("Yazan");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DernekYonetim.Models.Uye", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DernekYonetim.Models.Uye", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DernekYonetim.Models.Uye", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DernekYonetim.Models.Uye", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DernekYonetim.Models.Etkinlik", b =>
                {
                    b.Navigation("Kayitlar");
                });

            modelBuilder.Entity("DernekYonetim.Models.Proje", b =>
                {
                    b.Navigation("Belgeler");

                    b.Navigation("Guncellemeler");
                });

            modelBuilder.Entity("DernekYonetim.Models.Uye", b =>
                {
                    b.Navigation("Aidatlar");

                    b.Navigation("Belgeler");

                    b.Navigation("Bildirimler");

                    b.Navigation("EtkinlikKayitlari");
                });
#pragma warning restore 612, 618
        }
    }
}
